# ╔═════════════════════════════════════╗
# ║ Секция с общими параметрами запуска ║
# ║ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ║
# ┌───────────────────────────────────────────────────────┐
# │ Базовые параметры для разработчиков, можно не трогать │
# │ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ │
LOGLEVEL: DEBUG
HANDLER_PORT_RANGE: [8001, 8050]
HANDLER_INACTIVITY_TIMEOUT: 1800  # 30 минут
REDIS_HOST: 127.0.0.1
REDIS_DB: 0
REDIS_EXPIRE_DAYS: 14
# ┌─────────────────────────────────────────────────────────────┐
# │ Используемый порт Redis, изменить в соответствии со стендом │
# │ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ │
REDIS_PORT: 6379
# ┌─────────────────────────────────────────────────────────────────────────────┐
# │ Используемые ML-модели, изменить в соответствии со требованиями ассистентов │
# │ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ │
local_models:
  - name: 'bge'
    link: 'download link'
  - name: 'intfloat'
    link: 'download link'

# ╔═════════════════════════════════════╗
# ║ Секция с конфигурациями ассистентов ║
# ║ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ║
HANDLERS:
# ┌──────────────────────────────────┐
# │ Базовая информация об ассистенте │
# │ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼  │
  - name: 'Наименование ассистента, которое будет отображаться в пользовательском интерфейсе, не более 24 символов'
    task_type: 'Наименование ассистента на латинице (разрешенные символы: латиница, цифры, подчеркивание), например: new_assistant'
    version: 'Версия ИА (разрешенные символы: цифры, точка, латиница), например: 0.0.2dev'
    description: 'Описание ассистента'
# ┌──────────────────────────────────────────────────────────────────────────────────────┐
# │                    Информация о том, откуда брать код ассистента                     │
# │ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼  │
# ╔══════════════════════════════════════════════════════════════════════════════════════╗
# ║ ███ Нужно заполнить ЛИБО ссылку на репозиторий, ЛИБО путь к локальной директории ███ ║
# ╚══════════════════════════════════════════════════════════════════════════════════════╝
    source_dir_name: 'Путь к директории с кодом ассистента'
# ║ ███ ИЛИ ↕ ███ ║
    git_repo: 'Https адрес репозитория с кодом ассистента'
    git_branch: 'Ветка репозитория, из которой будет скопирован код ассистента, например: dev'
# ┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
# │            Информация о том, где находится основная интерфейсная функция ассистента (от корня ассистента)            │
# │ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼  │
# ╔══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
# ║ ███ Реализация функции должна соответствовать сигнатуре: def func(input: dict, **kwargs) -> str | dict           ███ ║
# ║ ███ Если функция возвращает словарь, обязательно должен быть ключ 'text', в качестве значения - ответ ассистента ███ ║
# ║ ███ О дополнительных ключах результирующего словаря можно узнать у разработчиков платформы                       ███ ║
# ╚══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
    interface_func_module: 'Путь от корня директории source_dir_name до модуля с функцией, например: multi_agent.main'
    interface_func_name: 'Наименование интерфейсной функции, например: get_answer'
# ┌───────────────────────────────────────────────────────────────────────────────────────┐
# │          (Опционально) Пути к дополнительным скриптам (от корня ассистента)           │
# │ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ │
# ╔═══════════════════════════════════════════════════════════════════════════════════════╗
# ║ ███ Скрипт загрузки/обновления базы знаний (БЗ) должен загружать БЗ в директорию, ███ ║
# ║ ███ указанную в переменной окружения KNOWLEDGE_BASE_DIR                           ███ ║
# ║ ███ Эта переменная также должна использоваться в ассистенте при обращениях к БЗ   ███ ║
# ╚═══════════════════════════════════════════════════════════════════════════════════════╝
    knowledge_base_loader: 'Путь к скрипту загрузки/обновления БЗ (*.sh или *.py), например: scripts/knowledge_base_loader.sh'
    service_launcher_script_path: 'Путь к скрипту запуска дополнительного сервиса (*.sh или *.py), например: scripts/start_flask.py'
    wait_for_service_launch_seconds: 30 # Время ожидания запуска дополнительного сервиса (в секундах), например: 30
# ┌──────────────────────────────────────────┐
# │ (Опционально) Флаг отключения ассистента │
# │ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼ ▼  │
    disabled: True

  - name: 'Локальная модель'
    task_type: 'local_model_handler'
    source_dir_name: 'local_model_handler'
    interface_func_module: 'generate_local_handler'
    interface_func_name: 'handle_task_with_local_model'
    version: '0.0.1'
    description: 'Описание локальной модели'
    disabled: True

  - name: 'Перемешать буквы'
    task_type: 'dummy_handler'
    source_dir_name: 'dummy_handler'
    interface_func_module: 'dummy_handler'
    interface_func_name: 'handle_task_dummy'
    version: '0.0.1'
    description: 'Описание dummy'
# TODO: добавить требование на self-check типов обработчиков отдельной функцией или модулем
