[project]
name = "worker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiofiles==24.1.0",
    "async-lru>=2.0.5",
    "asyncio-atexit>=1.0.1",
    "httpx>=0.28.1",
    "llama-cpp-python>=0.3.9",
    "loguru>=0.7.3",
    "pydantic>=2.11.4",
    "redis==5.2.1",
    "xxhash==3.5.0",
]
